apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
  containers:
  - name: ubuntu-sleeper
    image: cheebz/ubuntu-sleeper
    command: ["sleep"] # Overrides ENTRYPOINT instruction in Dockerfile
    args: ["10"] # Overrides CMD instruction in Dockerfile
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"