apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  namespace: httpd-ns
  labels:
    app: myapp
    type: deployment

spec:
  replicas: 3 # Desired number of replicas
  selector: # Selector to determine if Pod is a part of this ReplicaSet
    matchLabels:
      type: front-end
  template: # Pod to create, if needed
    metadata:
      name: httpd-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: httpd-container
          image: httpd:2.4-alpine
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
    
