apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: google-storage-silver # bind to storage class
  resources:
    requests:
      storage: 500Mi
