apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
rules:
  - resources: ["pods"]
    verbs: ["list", "get", "watch"]
    apiGroups: [""]
  - resources: ["ConfigMap"]
    verbs: ["create"]
    apiGroups: [""]