apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: google-storage-silver
provisioner: kubernetes.io/gce-pd
parameters: # specific to provider
  type: pd-standard
  replication-type: none

--- # Can create different `classes` hence the name
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: google-storage-gold
provisioner: kubernetes.io/gce-pd
parameters: # specific to provider
  type: pd-ssd
  replication-type: none
  
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: google-storage-platinum
provisioner: kubernetes.io/gce-pd
parameters: # specific to provider
  type: pd-ssd
  replication-type: regional-pd