apiVersion: v1
kind: Service
metadata:
  name: mysql-h
spec:
  selector:
    app: myapp
  ports:
  - port: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-h # headless service
  podManagementPolicy: OrderedReady # Parallel creates all replicas simultaneously
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data-volume
  # Note: when a Pod dies and is recreated, it is attached to the same PVC
  volumeClaimTemplates: # PVC is created for each Pod replica and storage class creates PV
  - metadata:
      name: data-volume
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: google-storage
      resources:
        requests:
          storage: 500Mi